### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dingo-d**
Added correct way of enqueuing Google Fonts

### CODE REVIEW

**Comment by dingo-d** [comment]
@taniarascia can you check this PR out, and merge it if it's ok? Thanks :)

**Comment by taniarascia** [comment]
Hi,

This is a nice bit of code, and thank you for contributing. I'm trying to keep all the snippets as short and concise as possible, and it just looks like a lot for a relatively simple function I have that works well enough.

**Comment by dingo-d** [comment]
Oh, ok. It's just that you are using `wp_print_styles` hook, which should never be used for enqueueing scripts or styles ;) I added the official way to add google fonts, and thought that it would be cool to have it in the snippets.

**Comment by taniarascia** [comment]
Ah, I did not know that. I'm guessing I should update it with `wp_enqueue_scripts()`? I just want to keep the code short.

**Comment by dingo-d** [comment]
Yep, `wp_enqueue_scripts` is the proper hook to use :)

**Pull request closed without merging**
